.PHONY: clean
clean:
	rm -rf bin

.PHONY: refresh
refresh:
	rm -rf obj
	dotnet restore

.PHONY: restore
restore:
	dotnet restore

.PHONY: dev
dev:
	dotnet run

.PHONY: build
build:
	dotnet build

.PHONY:	run
run:
	./bin/Debug/net8.0/Project
