name: Learn CSharp Exercises CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Build all exercises
      working-directory: content/1/
      run: |
        BASE_DIR=$(pwd)
        for dir in $(find . -maxdepth 1 -type d | tail -n +2); do
          echo "##[group]Processing $dir"
          cd "$dir"
          echo "Installing Dependencies in $dir"
          make restore
          echo "Building project in $dir"
          make build
          echo "Done, moving on..."
          cd "$BASE_DIR"
          echo "##[endgroup]"
        done
    - name: Run all exercises
      working-directory: content/1/
      run: |
        BASE_DIR=$(pwd)
        for dir in $(find . -maxdepth 1 -type d | tail -n +2); do
          echo "##[group]Processing $dir"
          cd "$dir"
          echo "Running project in $dir"
          make run
          echo "Done, moving on..."
          cd "$BASE_DIR"
          echo "##[endgroup]"
        done
